import Head from "next/head";
import styles from '../styles/Start.module.css';
import { SideMenu } from "../components";
import '@fontsource-variable/inter';
import { Image } from "@chakra-ui/react";

export default function Course() {
  return (
    <>
      <Head>
        <title>Курсы</title>
        <meta name="description" content="Generated by Zvir" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <SideMenu />
        <div style={{ marginLeft: '360px' }} >
            <p style={{ fontSize: '100px', color: '#000' }} >Курсы</p>
        </div>
      </main>

    </>
  );
}
